### PR TITLE
Reduce inventory when dispensed drug gets synced

### PR DESCRIPTION
**Pull request by sidtharthanan**
Reduce inventory when dispensed drug gets synced

### CODE REVIEW

**Comment by deepaucksharma** [comment]
Quotations are not created after taking this change in product set up.

**Comment by sidtharthanan** [comment]
We use this change set. We are able to use the system without problems. May be you could check the data setup you have.
Your mrs and erp may not have the same Drug you are trying with.
Your erp may have `no inventory for the Drug`.
You may not have setup the `Units to be Synced`.
Or it could be a problem with `Order Type - Shop mapping`.

**Comment by PrithviThakor** [comment]
Or there could be problem with period specified.

**Comment by deepaucksharma** [comment]
We have to compare the behaviour without the data set up. This change should not change the behaviour if someone wants to set up erp in a different way.

**Comment by sidtharthanan** [comment]
These are not something different. This are prerequisites of this feature.
IMHO, this is only way erp/this feature works and there is no other way.

**Pull request closed without merging**
